### ISSUE TITLE
bin/squashfs/unsquashfs not executable

### ISSUE THREAD

**Issue by zweckh** [PeterPawn/yf_bin#1]
Perhaps you could fix this in the repo or give a hint in the HOWTO that the unsquashfs command needs to be executable
`sudo chmod +x bin/squashfs/unsquashfs`

**Comment by PeterPawn** [comment]
I've removed the file (at least for the moment). It's still incomplete and did contain only four lines of shell code.

Some older description (mostly from IPPF) may still contain a reference to `bin/squashfs/unsquashfs`, but I've re-organized the FS structure there in the past, to support multiple platforms, kernels and C library versions, that were introduced step by step by the manufacturer or by myself.

The right binaries may be found (if they're present, what's not the case for all platforms) using the path `bin/squashfs/$(uname -r)/` - but it has to be taken into account, that the file names of the binaries changed, too.
